-- LMS Platform Database Schema
-- Designed for PostgreSQL

-- Curriculums Table (IGCSE, A-Levels, Pearson Edexcel)
CREATE TABLE curriculums (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,           -- "Cambridge IGCSE"
  slug TEXT UNIQUE NOT NULL,     -- "igcse"
  icon TEXT,                     -- Lucide icon name (e.g., "GraduationCap")
  color TEXT,                    -- Hex code (e.g., "#D92D20")
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Subjects Table (Math, Physics, Chemistry, etc.)
CREATE TABLE subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  curriculum_id BIGINT REFERENCES curriculums(id) ON DELETE CASCADE,
  title TEXT NOT NULL,           -- "Physics"
  slug TEXT NOT NULL,            -- "physics-0625"
  code TEXT,                     -- "0625"
  description TEXT,
  icon TEXT,                     -- Lucide icon name
  color TEXT,                    -- Hex code for subject accent
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(curriculum_id, slug)
);

-- Units Table (Major topic groupings within subjects)
CREATE TABLE units (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id BIGINT REFERENCES subjects(id) ON DELETE CASCADE,
  title TEXT NOT NULL,           -- "1. General Physics"
  order_index INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Lessons Table (Individual lesson topics within units)
CREATE TABLE lessons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_id BIGINT REFERENCES units(id) ON DELETE CASCADE,
  title TEXT NOT NULL,           -- "1.1 Length and Time"
  slug TEXT NOT NULL,            -- "length-and-time"
  content TEXT,                  -- Lesson content (markdown or HTML)
  order_index INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX idx_subjects_curriculum ON subjects(curriculum_id);
CREATE INDEX idx_units_subject ON units(subject_id);
CREATE INDEX idx_lessons_unit ON lessons(unit_id);
CREATE INDEX idx_units_order ON units(subject_id, order_index);
CREATE INDEX idx_lessons_order ON lessons(unit_id, order_index);
